// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "github.com/bizio/abc-user-service/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// EventConsumer is an autogenerated mock type for the EventConsumer type
type EventConsumer struct {
	mock.Mock
}

// Consume provides a mock function with no fields
func (_m *EventConsumer) Consume() (<-chan *domain.Event, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 <-chan *domain.Event
	var r1 error
	if rf, ok := ret.Get(0).(func() (<-chan *domain.Event, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() <-chan *domain.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *domain.Event)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventConsumer creates a new instance of EventConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventConsumer {
	mock := &EventConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
