// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"

	os "os"
)

// FileRepository is an autogenerated mock type for the FileRepository type
type FileRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: userID, filename
func (_m *FileRepository) Delete(userID string, filename string) error {
	ret := _m.Called(userID, filename)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(userID, filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteFiles provides a mock function with given fields: userID
func (_m *FileRepository) DeleteFiles(userID string) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: userID, filename
func (_m *FileRepository) Get(userID string, filename string) (*os.File, error) {
	ret := _m.Called(userID, filename)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*os.File, error)); ok {
		return rf(userID, filename)
	}
	if rf, ok := ret.Get(0).(func(string, string) *os.File); ok {
		r0 = rf(userID, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userID, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: userID
func (_m *FileRepository) List(userID string) ([]string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: userID, file
func (_m *FileRepository) Upload(userID string, file *multipart.FileHeader) (string, error) {
	ret := _m.Called(userID, file)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, *multipart.FileHeader) (string, error)); ok {
		return rf(userID, file)
	}
	if rf, ok := ret.Get(0).(func(string, *multipart.FileHeader) string); ok {
		r0 = rf(userID, file)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, *multipart.FileHeader) error); ok {
		r1 = rf(userID, file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFileRepository creates a new instance of FileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileRepository {
	mock := &FileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
